server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      enabled: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/	# View Resolver 설정
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cos?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl    
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false
      
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 59695039153-t9tuic1fsa8fcppo4lsr5ghkjhrquue6.apps.googleusercontent.com
            client-secret: zx8s1NVJA2XVcaZ7sWBD8ylv
            scope:
            - email
            - profile
            
          facebook:
            client-id: 270559447858270
            client-secret: dd920c04175f6b8b1789f53f9cf5d84e
            scope:
            - email
            - public_profile